# site
title: Grace Han
baseurl: ""
url: ""
favicon: "/assets/sample/ico.png"
g_analytics:

sass:
  sass_dir: _sass

# bio
header: Grace Han 
desc: >
  Personal Blog of Grace Han

# posts
date_format: "%Y"
post_title: Post
post_date: Date
post_cat: Category

# post detail
prev-next: true

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
