# site
title: Grace Han
baseurl: ""
url: ""
favicon: "/assets/sample/ico.png"
g_analytics: UA-12345678-1




sass:
  sass_dir: _sass

# bio
header: Grace Han 
desc: >
  Personal Blog of Grace Han

# posts
date_format: "%Y"
post_title: Story
post_date: Year
post_cat: Genre

# post detail
prev-next: true

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
